config/routes.rb
Rails.application.routes.draw do
  resources :posts

  devise_for :authors
  root 'posts#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [ :show, :edit, :update, :destroy ]

  def index
    @q = Post.order(created_at: :desc).ransack(params[:q])
    @posts = @q.result.page(params[:page]).per(2)
    @new_posts = Post.order(created_at: :desc).limit(5)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to "/posts/#{@post.id}"
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to "/posts/#{@post.id}"
  end

  def destroy
    @post.destroy
    redirect_to "/posts"
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :category)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">MyBlog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "トップページ", posts_path %></li>
        <li><%= link_to "新規投稿", new_post_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if author_signed_in? %>
          <li><%= link_to "設定変更", edit_author_registration_path %></li>
          <li><%= link_to "ログアウト", destroy_author_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", new_author_registration_path %></li>
          <li><%= link_to "ログイン", new_author_session_path %></li>
        <% end %>
      </ul>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyNewBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/posts/edit.html.erb
<div class="col-md-12">
  <h1>ブログ記事編集</h1>
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label "タイトル" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "カテゴリ" %>
      <%= f.text_field :category, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "本文" %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <%= f.submit '更新する', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="col-md-12">
  <div class="form-inline pull-right" style="margin-bottom:10px;">
    <%= search_form_for @q do |f| %>
      <div class="form-group">
        <%= f.search_field :title_or_body_cont, placeholder: "タイトルか本文を検索", class: "form-control" %>
        <%= f.submit "検索", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <% @posts.each do |post| %>
      <div class="article">
        <h2><%= post.title %></h2>
        <p><%= post.category %></p>
        <p><%= truncate(post.body, length: 50) %></p>
        <p>
          <%= link_to "続きを読む", post, class: 'btn btn-default' %>
        </p>
      </div>
    <% end %>
    <%= paginate @posts %>
  </div>

  <div class="col-md-4">
    <div class="thumbnail">
      <img src="#" alt="著者イメージ">
      <div class="caption">
        <h3>著者名<%=  %></h3>
        <p>著者詳細<%=  %></p>
      </div>
    </div>

    <div class="list-group">
      <% @new_posts.each do |post| %>
        <%= link_to post.title, post, class: "list-group-item" %>
      <% end %>
    </div>
    <h3>最新コメント一覧</h3>
  </div>
</div>

app/views/posts/new.html.erb
<div class="col-md-12">
  <h1>ブログ記事投稿</h1>
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label "タイトル" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "カテゴリ" %>
      <%= f.text_field :category, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "本文" %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <%= f.submit '登録する', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="col-md-12">
  <h1><%= @post.title %></h1>
  <p>カテゴリ: <%= @post.category %></p>
  <p>投稿日:<%= @post.created_at %></p>
  <hr>
  <p>
    <%= simple_format(@post.body) %>
  </p>
  <hr>
  <%= link_to "編集", edit_post_path(@post), class: "btn btn-default" %>
  <%= link_to "削除", post_path(@post), class: "btn btn-default", method: :delete %>
</div>